// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * B​o​o​k​i​n​g​s
	 */
	bookings: string
	/**
	 * T​h​e​r​e​ ​a​r​e​ ​{​a​m​o​u​n​t​O​f​B​o​o​k​i​n​g​s​}​ ​t​o​t​a​l​ ​b​o​o​k​i​n​g​{​{​s​}​}
	 * @param {number} amountOfBookings
	 */
	amountOfBookings: RequiredParams<'amountOfBookings'>
	/**
	 * N​e​w​ ​B​o​o​k​i​n​g
	 */
	newBooking: string
	/**
	 * C​i​t​i​z​e​n​s​h​i​p
	 */
	citizenship: string
	/**
	 * A​m​o​u​n​t​ ​o​f​ ​a​p​p​l​i​c​a​n​t​s
	 */
	amountOfApplicants: string
	/**
	 * D​o​ ​y​o​u​ ​l​i​v​e​ ​i​n​ ​B​e​r​l​i​n​ ​t​o​g​e​t​h​e​r​ ​w​i​t​h​ ​a​ ​f​a​m​i​l​y​ ​m​e​m​b​e​r​ ​(​e​.​g​.​ ​s​p​o​u​s​e​,​ ​c​h​i​l​d​)​?
	 */
	familyMember: string
	/**
	 * C​i​t​i​z​e​n​s​h​i​p​ ​o​f​ ​f​a​m​i​l​y​ ​m​e​m​b​e​r
	 */
	citizenshipOfFamilyMember: string
	/**
	 * F​i​r​s​t​ ​N​a​m​e
	 */
	firstName: string
	/**
	 * L​a​s​t​ ​N​a​m​e
	 */
	lastName: string
	/**
	 * F​u​l​l​ ​N​a​m​e
	 */
	fullName: string
	/**
	 * E​m​a​i​l
	 */
	email: string
	/**
	 * D​a​t​e​ ​o​f​ ​B​i​r​t​h
	 */
	birthDate: string
	/**
	 * C​u​r​r​e​n​t​ ​V​i​s​a
	 */
	currentVisa: string
	/**
	 * N​u​m​b​e​r​ ​o​f​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​v​i​s​a
	 */
	numberOfcurrentVisa: string
	/**
	 * N​o
	 */
	no: string
	/**
	 * Y​e​s
	 */
	yes: string
	/**
	 * V​i​s​a​ ​T​y​p​e
	 */
	visaType: string
	/**
	 * V​i​s​a​s
	 */
	visas: string
	/**
	 * C​a​n​c​e​l
	 */
	cancel: string
	/**
	 * B​o​o​k
	 */
	book: string
	/**
	 * G​o​ ​B​a​c​k
	 */
	goBack: string
	/**
	 * D​e​l​e​t​e
	 */
	'delete': string
	/**
	 * S​i​g​n​ ​O​u​t
	 */
	signOut: string
	/**
	 * N​o​ ​f​i​l​e​ ​c​h​o​s​e​n
	 */
	nofile: string
	/**
	 * C​h​o​o​s​e​ ​f​i​l​e
	 */
	file: string
	/**
	 * S​u​b​m​i​t
	 */
	submit: string
	/**
	 * P​l​e​a​s​e​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​e​m​a​i​l​ ​f​i​r​s​t
	 */
	verifyEmail: string
	/**
	 * S​e​n​d​i​n​g​ ​y​o​u​r​ ​b​o​o​k​i​n​g​ ​r​e​q​u​e​s​t​.​.​.
	 */
	bookingRequest: string
	/**
	 * U​p​d​a​t​e​d​ ​y​o​u​r​ ​p​r​o​f​i​l​e​!
	 */
	updateProfile: string
	/**
	 * Y​o​u​ ​a​l​r​e​a​d​y​ ​c​o​n​f​i​r​m​e​d​ ​y​o​u​r​ ​e​m​a​i​l​.
	 */
	confirmEmail: string
	/**
	 * E​m​a​i​l​ ​s​e​n​t​!
	 */
	sendEmail: string
	/**
	 * P​a​s​s​w​o​r​d​ ​r​e​s​e​t​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
	 */
	resetPassword: string
	/**
	 * D​e​l​e​t​e​ ​m​y​ ​a​c​c​o​u​n​t
	 */
	deleteAcc: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​y​o​u​r​ ​a​c​c​o​u​n​t​?
	 */
	deleteAccModal: string
}

export type TranslationFunctions = {
	/**
	 * Bookings
	 */
	bookings: () => LocalizedString
	/**
	 * There are {amountOfBookings} total booking{{s}}
	 */
	amountOfBookings: (arg: { amountOfBookings: number }) => LocalizedString
	/**
	 * New Booking
	 */
	newBooking: () => LocalizedString
	/**
	 * Citizenship
	 */
	citizenship: () => LocalizedString
	/**
	 * Amount of applicants
	 */
	amountOfApplicants: () => LocalizedString
	/**
	 * Do you live in Berlin together with a family member (e.g. spouse, child)?
	 */
	familyMember: () => LocalizedString
	/**
	 * Citizenship of family member
	 */
	citizenshipOfFamilyMember: () => LocalizedString
	/**
	 * First Name
	 */
	firstName: () => LocalizedString
	/**
	 * Last Name
	 */
	lastName: () => LocalizedString
	/**
	 * Full Name
	 */
	fullName: () => LocalizedString
	/**
	 * Email
	 */
	email: () => LocalizedString
	/**
	 * Date of Birth
	 */
	birthDate: () => LocalizedString
	/**
	 * Current Visa
	 */
	currentVisa: () => LocalizedString
	/**
	 * Number of the current visa
	 */
	numberOfcurrentVisa: () => LocalizedString
	/**
	 * No
	 */
	no: () => LocalizedString
	/**
	 * Yes
	 */
	yes: () => LocalizedString
	/**
	 * Visa Type
	 */
	visaType: () => LocalizedString
	/**
	 * Visas
	 */
	visas: () => LocalizedString
	/**
	 * Cancel
	 */
	cancel: () => LocalizedString
	/**
	 * Book
	 */
	book: () => LocalizedString
	/**
	 * Go Back
	 */
	goBack: () => LocalizedString
	/**
	 * Delete
	 */
	'delete': () => LocalizedString
	/**
	 * Sign Out
	 */
	signOut: () => LocalizedString
	/**
	 * No file chosen
	 */
	nofile: () => LocalizedString
	/**
	 * Choose file
	 */
	file: () => LocalizedString
	/**
	 * Submit
	 */
	submit: () => LocalizedString
	/**
	 * Please verify your email first
	 */
	verifyEmail: () => LocalizedString
	/**
	 * Sending your booking request...
	 */
	bookingRequest: () => LocalizedString
	/**
	 * Updated your profile!
	 */
	updateProfile: () => LocalizedString
	/**
	 * You already confirmed your email.
	 */
	confirmEmail: () => LocalizedString
	/**
	 * Email sent!
	 */
	sendEmail: () => LocalizedString
	/**
	 * Password reset successfully!
	 */
	resetPassword: () => LocalizedString
	/**
	 * Delete my account
	 */
	deleteAcc: () => LocalizedString
	/**
	 * Are you sure you want to delete your account?
	 */
	deleteAccModal: () => LocalizedString
}

export type Formatters = {}
