export const config = {
	de: {
		citizenship: [
			'*staatenlos',
			'*ungeklärt (Palästinenser und Kurden aus dem Libanon)',
			'*ungeklärt / Palästinenser aus Syrien (Familienname A – E)',
			'*ungeklärt / Palästinenser aus Syrien (Familienname F – Z)',
			'Afghanistan',
			'Ägypten',
			'Albanien',
			'Algerien',
			'Andorra',
			'Angola',
			'Antigua und Barbuda',
			'Äquatorialguinea',
			'Argentinien',
			'Armenien',
			'Aserbaidschan',
			'Äthiopien',
			'Australien',
			'Bahamas',
			'Bahrain',
			'Bangladesch',
			'Barbados',
			'Belarus',
			'Belize',
			'Benin',
			'Bhutan',
			'Bolivien',
			'Bosnien und Herzegowina',
			'Botsuana',
			'Brasilien',
			'britisches Überseegebiet in Afrika',
			'britisches Überseegebiet in Amerika',
			'britisches Überseegebiet in Asien',
			'britisches Überseegebiet in Australien',
			'britisches Überseegebiet in Europa',
			'Brunei Darussalam',
			'Burkina Faso',
			'Burundi',
			'Chile',
			'China',
			'Costa Rica',
			'Dänemark',
			'Deutschland',
			'Dominica',
			'Dominikanische Republik',
			'Dschibuti',
			'Ecuador',
			'El Salvador',
			'Eritrea',
			'Estland',
			'Fidschi',
			'Finnland',
			'Frankreich',
			'Gabun',
			'Gambia',
			'Georgien',
			'Ghana',
			'Grenada',
			'Griechenland',
			'Guatemala',
			'Guinea',
			'Guinea-Bissau',
			'Guyana',
			'Haiti',
			'Honduras',
			'Indien',
			'Indonesien',
			'Irak',
			'Iran, Islamische Republik',
			'Israel',
			'Jamaika',
			'Japan',
			'Jordanien',
			'Kambodscha',
			'Kamerun',
			'Kanada',
			'Kap Verde',
			'Kasachstan',
			'Kenia',
			'Kirgisistan',
			'Kiribati',
			'Kolumbien',
			'Komoren',
			'Kongo',
			'Kongo, Demokratische Republik',
			'Kongo, Republik',
			'Kroatien',
			'Kuba',
			'Kuwait',
			'Laos, Demokratische Volksrepublik',
			'Lesotho',
			'Lettland',
			'Libanon',
			'Liberia',
			'Libyen',
			'Liechtenstein',
			'Litauen',
			'Luxemburg',
			'Madagaskar',
			'Malawi',
			'Malaysia',
			'Malediven',
			'Mali',
			'Malta',
			'Marokko',
			'Marshallinseln',
			'Mauretanien',
			'Mauritius',
			'Mexiko',
			'Mikronesien, Föderierte Staaten von',
			'Moldawien, Republik',
			'Monaco',
			'Mongolei',
			'Mosambik',
			'Myanmar',
			'Namibia',
			'Nauru',
			'Nepal',
			'Neuseeland',
			'Nicaragua',
			'Niederlande',
			'Niger',
			'Nigeria',
			'Nordkorea',
			'Norwegen',
			'Oman',
			'Österreich',
			'Pakistan',
			'Palau',
			'Panama',
			'Papua-Neuguinea',
			'Paraguay',
			'Peru',
			'Philippinen',
			'Polen',
			'Portugal',
			'Ruanda',
			'Rumänien',
			'Russische Föderation',
			'Salomonen',
			'Sambia',
			'Samoa',
			'San Marino',
			'São Tomé und Príncipe',
			'Saudi-Arabien',
			'Schweden',
			'Schweiz',
			'Senegal',
			'Serbien und Montenegro',
			'Seychellen',
			'Sierra Leone',
			'Simbabwe',
			'Singapur',
			'Slowakei',
			'Slowenien',
			'Somalia',
			'Spanien',
			'Sri Lanka',
			'St. Kitts und Nevis',
			'St. Lucia',
			'St. Vincent und die Grenadinen',
			'Südafrika',
			'Sudan',
			'Südkorea',
			'Suriname',
			'Swasiland',
			'Syrien, Arabische Republik',
			'Tadschikistan',
			'Tansania, Vereinigte Republik',
			'Thailand',
			'Togo',
			'Tonga',
			'Trinidad und Tobago',
			'Tschad',
			'Tschechische Republik',
			'Tunesien',
			'Turkmenistan',
			'Tuvalu',
			'Uganda',
			'Ukraine',
			'Ungarn',
			'Uruguay',
			'Usbekistan',
			'Vanuatu',
			'Vatikanstadt',
			'Venezuela',
			'Vereinigte Arabische Emirate',
			'Vereinigte Staaten von Amerika',
			'Vietnam',
			'Zentralafrikanische Republik'
		],
		applicant: [
			'eine Person',
			'zwei Personen',
			'drei Personen',
			'vier Personen',
			'fünf Personen',
			'sechs Personen',
			'sieben Personen',
			'acht Personen'
		],
		visaType: [
			'Aufenthaltstitel - beantragen',
			'Aufenthaltstitel - verlängern',
			'Aufenthaltstitel in einen neuen Pass eintragen lassen',
			'Niederlassungserlaubnis beantragen'
		]
	}
};
